test_that("Chromatograms works", {
    chs <- new("Chromatograms")
    expect_equal(nrow(chs), 0)
    expect_equal(ncol(chs), 0)
    chs <- Chromatograms()
    expect_equal(nrow(chs), 0)
    expect_equal(ncol(chs), 0)
    ## Errors:
    chs@.Data <- matrix(1:4)
    expect_error(validObject(chs))
    expect_error(Chromatograms(1:4))
    ch <- new("Chromatogram")
    ch_list <- list(ch, ch, ch, ch, ch, ch, ch, ch)
    chs <- Chromatograms(ch_list, nrow = 2)
    expect_equal(length(chs[1, 1][[1]]), 0)
    chs[2, 1] <- list(Chromatogram(1:10, 1:10))
    expect_equal(length(chs[2, 1][[1]]), 10)
    expect_equal(chs[, 1], c(ch, Chromatogram(1:10, 1:10)))
})
