// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// imp_neighbour_avg
NumericMatrix imp_neighbour_avg(NumericMatrix x, double k);
RcppExport SEXP MSnbase_imp_neighbour_avg(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(imp_neighbour_avg(x, k));
    return __result;
END_RCPP
}
